language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: eMyBICv+FZICchpTGJtSaS5wSjGqI/ApDm10XdYqgD+ZUVLIdfE0bgFAlVWBBBWs7thAO+UYi66+N+fTi2UFioataRwIQMivRxam2mBRMYH/yLaixzU/2ygafOOEMdg2YlvvZrdfNlAPia6/9A4klcH9p59zSwBuHx04x6XfdM1kLR72Xjx1MOmrznLjmE5vi5XAjQRlNzxMkWqnxC19Szt2ASlI/jTfr9Q9gvhiiIg4tqZ9xVTRMMHn2M3UrCltv+IuTcIwIZy1dAsF0DXrJeXyPDQ3AyeNn1S+4ySPGCYI6yrjV4gn6MDut+8IsLonV3ISdWyyxzKeAw53TR/YFbfFXR1W89XE5OncY6Kr9G0mZPI0kOfv12lu9jRyxsyZ6CrH139LGTtuRf27BqBef2vGfBdSZeYI8EuBOgAVdJ9qA6WNhFDe533kWxE9mojjxyzBbNMNefRjrBzn2qdDQ4O+3KP2FZNTB7xDq/0ugvJ3QyKtAisU0R5+6kdxIxduP6hMVknlyCLPFwewRpqu9tIYrLxf7cNYbEzrpgiUBpf9JG9ikXpJwNbHQIKXkjrMcKhmogsFTgZ0oQKQs6O1k0+26JKHCfRokO4Dja7AnqfNqvd0oRVz4xiN3JJG4rvLxm/fjvrXA5l1A90kD0nHzYOepm2daN0tkSEPLW6wd7w=
  app: morning-dawn-48128
  on:
    repo: davepatel95/Node-Capstone
